const signup = (req, res,saltRounds, pool) => {
  console.log('Inside signup module:');
  console.log(req.body);
  const { username } = req.body;
  const { emailId } = req.body;
  const { password } = req.body;
  
  let tableName = 'USERS';

  const alreadyPresentSql = `SELECT * FROM ${tableName} WHERE emailId = '${emailId}'`;
  pool.query(alreadyPresentSql, (err, searchResult) => {
    if (err) {
      console.log(err);
      res.send('Error');
    }
    if (searchResult.length > 0) {
      console.log(`${emailId}  already exists`);
      res.send('Exists');
    } else {
      
        
        let insertSql = '';
        
          insertSql = `INSERT INTO ${tableName} (username,emailId,password) VALUES ('${username}', '${emailId}', '${password}')`;
       
        pool.query(insertSql, (insertError, result) => {
          if (insertError) {
            console.log(insertError);
            res.send('Error');
          }
          console.log(result);
          console.log(`User: ${emailId} created in Table: ${tableName} with Autogenerated ID: ${result.insertID}`);
          res.send(`User: ${emailId} created in Table: ${tableName} with Autogenerated ID: ${result.insertId}`);
          
        });
     
    }
  });
};

exports.signup = signup;
